import { prisma } from '../prisma';
import { RoleType } from '../models/types';
import { AuthUser } from '../middleware/auth';
import { AppError } from '../middleware/errorHandler';
import { AuditService } from './AuditService';
import {
  BUCKET_NAME,
  createSignedDocumentUrl,
  deleteSpendingDocument,
  uploadSpendingDocument,
} from '../lib/supabase';

const MAX_FILE_BYTES = 10 * 1024 * 1024;

const ALLOWED_MIME_TYPES = new Set([
  'application/pdf',
  'image/png',
  'image/jpeg',
  'image/webp',
  'text/csv',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-excel',
]);

/**
 * DocumentService — Supabase Storage backed supporting documents for spending
 * requests.
 *
 * Binary content lives in a PRIVATE Supabase Storage bucket. Only metadata
 * (storage path, file name, mime type, size, uploader, owning request) is
 * persisted in Supabase PostgreSQL through the `SpendingDocument` table.
 *
 * Authorization mirrors the existing ATCS RBAC model and is enforced on every
 * operation:
 *   - EMPLOYEE : only documents on their own spending requests
 *   - MANAGER  : documents on spending requests of their own department
 *   - FINANCE  : all documents
 *   - ADMIN    : all documents
 * No public URLs are ever produced; downloads are short-lived signed URLs
 * generated by the backend after the authorization check passes.
 */
export class DocumentService {
  /**
   * Resolves the spending request and asserts the caller may access its documents.
   */
  private static async authorizeRequest(requestId: string, user: AuthUser) {
    const spendingRequest = await prisma.spendingRequest.findUnique({
      where: { id: requestId },
      select: {
        id: true,
        employeeId: true,
        departmentId: true,
        status: true,
      },
    });

    if (!spendingRequest) {
      throw new AppError('Spending request not found.', 404, 'REQUEST_NOT_FOUND');
    }

    const isGlobalRole = user.role === RoleType.ADMIN || user.role === RoleType.FINANCE;
    if (isGlobalRole) return spendingRequest;

    if (user.role === RoleType.EMPLOYEE) {
      if (spendingRequest.employeeId !== user.id) {
        throw new AppError(
          'Access denied: you may only access documents on your own spending requests.',
          403,
          'DOCUMENT_ACCESS_DENIED'
        );
      }
      return spendingRequest;
    }

    if (user.role === RoleType.MANAGER) {
      if (!user.departmentId || spendingRequest.departmentId !== user.departmentId) {
        throw new AppError(
          'Access denied: this document belongs to another department.',
          403,
          'CROSS_DEPARTMENT_FORBIDDEN'
        );
      }
      return spendingRequest;
    }

    throw new AppError('Your role is not authorized to access spending documents.', 403, 'FORBIDDEN_ROLE');
  }

  /**
   * Uploads a supporting document and persists its metadata in PostgreSQL.
   */
  public static async uploadDocument(
    spendingRequestId: string,
    user: AuthUser,
    file: { originalname: string; mimetype: string; size: number; buffer: Buffer },
    documentType = 'SUPPORTING'
  ) {
    const spendingRequest = await this.authorizeRequest(spendingRequestId, user);

    if (!file || !file.buffer || file.buffer.length === 0) {
      throw new AppError('No file content received.', 400, 'EMPTY_FILE');
    }
    if (file.size > MAX_FILE_BYTES) {
      throw new AppError(
        `File exceeds the ${MAX_FILE_BYTES / (1024 * 1024)} MB limit for supporting documents.`,
        413,
        'FILE_TOO_LARGE'
      );
    }
    if (!ALLOWED_MIME_TYPES.has(file.mimetype)) {
      throw new AppError(
        `Unsupported file type '${file.mimetype}'. Allowed: PDF, PNG, JPEG, WEBP, CSV, XLS, XLSX.`,
        415,
        'UNSUPPORTED_FILE_TYPE'
      );
    }

    const { storagePath, error } = await uploadSpendingDocument({
      spendingRequestId,
      departmentId: spendingRequest.departmentId,
      fileName: file.originalname,
      fileBuffer: file.buffer,
      mimeType: file.mimetype,
    });

    if (error || !storagePath) {
      throw new AppError(
        `Upload to Supabase Storage failed: ${error || 'unknown error'}. No record was created.`,
        502,
        'STORAGE_UPLOAD_FAILED'
      );
    }

    const document = await prisma.spendingDocument.create({
      data: {
        spendingRequestId,
        storagePath,
        fileName: file.originalname,
        mimeType: file.mimetype,
        sizeBytes: file.size,
        documentType,
        uploadedBy: user.id,
      },
    });

    await AuditService.createLog({
      userId: user.id,
      action: 'SPENDING_DOCUMENT_UPLOADED',
      entityType: 'SpendingDocument',
      entityId: document.id,
      newValue: JSON.stringify({
        spendingRequestId,
        fileName: document.fileName,
        mimeType: document.mimeType,
        sizeBytes: document.sizeBytes,
        bucket: BUCKET_NAME,
      }),
      metadata: JSON.stringify({ storagePath }),
    });

    return document;
  }

  /**
   * Lists document metadata for a spending request (never exposes storage paths).
   */
  public static async listDocuments(spendingRequestId: string, user: AuthUser) {
    await this.authorizeRequest(spendingRequestId, user);

    return prisma.spendingDocument.findMany({
      where: { spendingRequestId },
      select: {
        id: true,
        spendingRequestId: true,
        fileName: true,
        mimeType: true,
        sizeBytes: true,
        documentType: true,
        uploadedBy: true,
        createdAt: true,
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Issues a short-lived signed URL after the RBAC check has passed.
   */
  public static async getSignedUrl(documentId: string, user: AuthUser, expiresInSeconds = 300) {
    const document = await prisma.spendingDocument.findUnique({ where: { id: documentId } });
    if (!document) {
      throw new AppError('Document not found.', 404, 'DOCUMENT_NOT_FOUND');
    }

    await this.authorizeRequest(document.spendingRequestId, user);

    const { signedUrl, error } = await createSignedDocumentUrl(document.storagePath, expiresInSeconds);
    if (error || !signedUrl) {
      throw new AppError(
        `Could not generate an authorized download link: ${error || 'unknown error'}.`,
        502,
        'SIGNED_URL_FAILED'
      );
    }

    await AuditService.createLog({
      userId: user.id,
      action: 'SPENDING_DOCUMENT_ACCESSED',
      entityType: 'SpendingDocument',
      entityId: document.id,
      metadata: JSON.stringify({ expiresInSeconds }),
    });

    return { signedUrl, expiresInSeconds, fileName: document.fileName };
  }

  /**
   * Removes a document from Storage and PostgreSQL.
   */
  public static async deleteDocument(documentId: string, user: AuthUser) {
    const document = await prisma.spendingDocument.findUnique({ where: { id: documentId } });
    if (!document) {
      throw new AppError('Document not found.', 404, 'DOCUMENT_NOT_FOUND');
    }

    const spendingRequest = await this.authorizeRequest(document.spendingRequestId, user);

    const isOwnerOfDocument = document.uploadedBy === user.id;
    const isGlobalRole = user.role === RoleType.ADMIN || user.role === RoleType.FINANCE;
    if (!isOwnerOfDocument && !isGlobalRole) {
      throw new AppError('Only the uploader, Finance or Admin may delete this document.', 403, 'DOCUMENT_ACCESS_DENIED');
    }

    const { success, error } = await deleteSpendingDocument(document.storagePath);
    if (!success) {
      throw new AppError(
        `Failed to remove the object from Supabase Storage: ${error || 'unknown error'}. Metadata was retained.`,
        502,
        'STORAGE_DELETE_FAILED'
      );
    }

    await prisma.spendingDocument.delete({ where: { id: document.id } });

    await AuditService.createLog({
      userId: user.id,
      action: 'SPENDING_DOCUMENT_DELETED',
      entityType: 'SpendingDocument',
      entityId: document.id,
      previousValue: JSON.stringify({ fileName: document.fileName, spendingRequestId: document.spendingRequestId }),
      metadata: JSON.stringify({ departmentId: spendingRequest.departmentId }),
    });

    return { id: document.id, deleted: true };
  }
}
